export const GENERATE_NEW_NUMBER = 'GNN';
export const GENERATE_NEW_NUMBER_SUCCESS = 'GNN_S';

export const GET_IPSUM_SUCCESS = 'GET_IPSUM_SUCCESS';
export const GET_IPSUM_FAILED = 'GET_IPSUM_FAILED';

export const MOVE_CURSOR_NEXT = 'MOVE_CURSOR_NEXT';
export const ELEMENT_COMPLETE = 'ELEMENT_COMPLETE';
